# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# ==============================================================================
# CodeRabbit Configuration for ReparaYa
# ==============================================================================
# Documentación: https://docs.coderabbit.ai/reference/configuration
# Schema v2: https://coderabbit.ai/integrations/schema.v2.json
# ==============================================================================

# ------------------------------------------------------------------------------
# CONFIGURACIÓN GENERAL
# ------------------------------------------------------------------------------
language: es-ES
early_access: false
enable_free_tier: true

# Instrucciones de tono personalizadas
tone_instructions: |
  - Usa un tono profesional pero amigable
  - Proporciona sugerencias constructivas
  - Enfócate en mejoras de código, no solo en errores
  - Reconoce cuando el código está bien hecho

# ------------------------------------------------------------------------------
# CONFIGURACIÓN DE REVIEWS
# ------------------------------------------------------------------------------
reviews:
  # Perfil de revisión (chill = menos estricto, assertive = más estricto)
  profile: chill

  # Generar resumen de alto nivel
  high_level_summary: true
  high_level_summary_in_walkthrough: false

  # Configuración de auto-review
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false

    # Palabras clave en título para ignorar review automático
    ignore_title_keywords:
      - "wip"
      - "draft"
      - "do not review"

    # Solo revisar PRs hacia la rama 'dev'
    # PRs hacia 'main' se hacen desde 'dev' después de validación completa
    base_branches:
      - dev

  # Filtros de rutas (formato glob negativo con !)
  path_filters:
    # Excluir archivos de node_modules, builds y tests
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/.next/**"
    - "!**/coverage/**"
    - "!**/*.test.ts"
    - "!**/*.test.tsx"
    - "!**/*.spec.ts"
    - "!**/package-lock.json"
    - "!**/pnpm-lock.yaml"

  # Instrucciones personalizadas por ruta
  path_instructions:
    - path: "apps/web/**/*.ts"
      instructions: |
        ReparaYa - Contexto del proyecto:
        - Stack: Next.js 14 + TypeScript + Prisma + PostgreSQL
        - Autenticación: Clerk
        - Pagos: Stripe (Checkout + Connect)
        - Cloud: AWS (S3, SES, Location Service)

        Al revisar código TypeScript, verifica:

        **Seguridad:**
        - Autorización correcta (roles: client, contractor, admin)
        - Sanitización de inputs (especialmente en mensajería)
        - No exponer datos sensibles en APIs públicas
        - Verificación de firmas en webhooks (Stripe, Clerk)

        **Performance:**
        - Queries eficientes (usar includes de Prisma selectivamente)
        - Índices apropiados en búsquedas
        - No hacer llamadas a DB en loops

        **Arquitectura:**
        - Separación de capas (presentación → servicios → repositorios)
        - Lógica de negocio en servicios, no en API routes
        - DTOs y validaciones con Zod

        **Código limpio:**
        - Nombres descriptivos (camelCase para variables, PascalCase para componentes)
        - No usar `any` (TypeScript strict mode)
        - Comentarios útiles para lógica compleja

    - path: "apps/web/**/*.tsx"
      instructions: |
        Al revisar componentes React:
        - Verificar uso correcto de hooks (useEffect, useState, etc.)
        - Componentes deben ser reutilizables y modulares
        - Manejar estados de loading y error
        - Accesibilidad (aria-labels, roles semánticos)
        - Performance (memoización cuando sea necesario)

    - path: "openspec/**/*.md"
      instructions: |
        Al revisar especificaciones de OpenSpec:
        - Verificar que los contratos estén bien definidos
        - Asegurar trazabilidad con requisitos (RF-XXX, RNF-XXX)
        - Validar que el plan de testing esté incluido
        - Coherencia con la arquitectura del proyecto

    - path: "docs/md/**/*.md"
      instructions: |
        Al revisar documentación:
        - Verificar claridad y coherencia
        - Asegurar que ejemplos de código sean válidos
        - Links internos y externos funcionales

  # Herramientas de análisis estático
  tools:
    eslint:
      enabled: true

    gitleaks:
      enabled: true

    markdownlint:
      enabled: true

# ------------------------------------------------------------------------------
# CONFIGURACIÓN DE CHAT
# ------------------------------------------------------------------------------
chat:
  auto_reply: true

# ------------------------------------------------------------------------------
# BASE DE CONOCIMIENTO
# ------------------------------------------------------------------------------
knowledge_base:
  # No opt-out de la base de conocimiento
  opt_out: false

  # Guidelines de código del proyecto
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CLAUDE.md"
      - "**/openspec/project.md"
      - "**/docs/md/architecture-overview.md"

  # Búsqueda web para contexto adicional
  web_search:
    enabled: true

  # Scope de learnings
  learnings:
    scope: auto

  # Scope de issues
  issues:
    scope: auto
