# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Configuration for ReparaYa
# https://docs.coderabbit.ai/reference/configuration

# Language
language: es-ES

# Review tone - instructions for all reviews
tone_instructions: |
  ReparaYa es una plataforma de marketplace para servicios de reparación y mantenimiento.

  Stack: Next.js 14 + TypeScript + PostgreSQL + Prisma + Clerk + Stripe
  Arquitectura: Monolito modular organizado por dominios

  Al revisar PRs de ReparaYa, presta atención a:

  1. **Seguridad**:
     - Autorización correcta (verificar roles: client, contractor, admin)
     - Sanitización de inputs (especialmente en mensajería)
     - No exponer datos sensibles en APIs públicas
     - Verificación de firmas en webhooks (Stripe, Clerk)

  2. **Performance**:
     - Queries eficientes (usar includes de Prisma selectivamente)
     - Índices apropiados en búsquedas
     - No hacer llamadas a DB en loops

  3. **Arquitectura**:
     - Separación de capas (presentación → servicios → repositorios)
     - Lógica de negocio en servicios, no en API routes
     - DTOs y validaciones con Zod

  4. **Testing**:
     - Tests unitarios para lógica de negocio
     - Tests de integración para endpoints
     - Verificar que se mantiene cobertura ≥ 70%

  5. **Código limpio**:
     - Nombres descriptivos (camelCase para variables, PascalCase para componentes)
     - No usar `any` (TypeScript strict mode)
     - Comentarios útiles (TODO, FIXME)
     - Seguir convenciones de Conventional Commits

  6. **Documentación**:
     - READMEs actualizados en módulos nuevos
     - Comentarios JSDoc en funciones públicas
     - Actualizar specs de OpenSpec si hay cambios arquitectónicos

  Usa un tono profesional pero amigable. Proporciona sugerencias constructivas. Reconoce cuando el código está bien hecho.

# Review settings
reviews:
  # Review profile
  profile: chill  # Options: chill, assertive

  # Request changes workflow
  request_changes_workflow: true

  # High level summary
  high_level_summary: true

  # Review status
  review_status: true

  # Auto-review configuration
  auto_review:
    enabled: true
    base_branches:
      - dev
      - main
    drafts: false
    auto_incremental_review: true

  # Path-specific instructions
  path_instructions:
    - path: "apps/web/src/modules/**/*.ts"
      instructions: |
        Este es código de lógica de negocio de ReparaYa. Verifica:
        - Validaciones con Zod correctas
        - Manejo de errores robusto
        - Queries de Prisma optimizadas
        - No usar `any` en TypeScript

    - path: "apps/web/src/app/**/*.ts"
      instructions: |
        Este es código de API routes. Verifica:
        - Autenticación y autorización por rol
        - Validación de inputs sanitizados
        - Respuestas de error apropiadas
        - No exponer datos sensibles

    - path: "apps/web/**/*.test.ts"
      instructions: |
        Código de tests. Verifica:
        - Mocks apropiados de dependencias externas
        - Casos de prueba completos
        - Nombres descriptivos de tests
        - No usar datos reales en tests

    - path: "docs/md/**/*.md"
      instructions: |
        Documentación del proyecto. Verifica:
        - Claridad y precisión
        - Actualizaciones con cambios de código
        - Enlaces correctos a specs
        - Ejemplos completos y funcionales

    - path: "openspec/**/*.md"
      instructions: |
        Especificaciones de OpenSpec. Verifica:
        - Consistencia con el código implementado
        - Testing plan completo
        - Requisitos bien definidos
        - No hay conflictos con specs existentes

    - path: "apps/web/prisma/**"
      instructions: |
        Schema de base de datos. Verifica:
        - Nombres en camelCase para campos
        - Índices en campos de búsqueda frecuente
        - Relaciones bidireccionales correctas
        - Tipos apropiados (Decimal para dinero, UUID para IDs)

  # Pre-merge checks
  pre_merge_checks:
    title: warning
    description: warning
    docstrings: warning

  # Tools configuration
  tools:
    eslint:
      enabled: true
    markdownlint:
      enabled: false
