# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Configuration for ReparaYa
# https://docs.coderabbit.ai/reference/configuration
#
# NOTA: tone_instructions tiene límite de 250 caracteres.
# Las instrucciones detalladas están en path_instructions (línea 35+)

# Language
language: es-ES

# Review tone - instructions for all reviews (max 250 chars)
tone_instructions: "ReparaYa marketplace: Next.js + TS + Prisma. Prioriza seguridad (auth/roles), performance (Prisma queries), arquitectura modular, testing ≥70%, TypeScript strict. Tono profesional y constructivo."

# Review settings
reviews:
  # Review profile
  profile: chill  # Options: chill, assertive

  # Request changes workflow
  request_changes_workflow: true

  # High level summary
  high_level_summary: true

  # Review status
  review_status: true

  # Auto-review configuration
  auto_review:
    enabled: true
    base_branches:
      - dev
      - main
    drafts: false
    auto_incremental_review: true

  # Path-specific instructions
  path_instructions:
    - path: "apps/web/src/modules/**/*.ts"
      instructions: |
        Este es código de lógica de negocio de ReparaYa. Verifica:
        - Validaciones con Zod correctas
        - Manejo de errores robusto
        - Queries de Prisma optimizadas
        - No usar `any` en TypeScript

    - path: "apps/web/src/app/**/*.ts"
      instructions: |
        Este es código de API routes. Verifica:
        - Autenticación y autorización por rol
        - Validación de inputs sanitizados
        - Respuestas de error apropiadas
        - No exponer datos sensibles

    - path: "apps/web/**/*.test.ts"
      instructions: |
        Código de tests. Verifica:
        - Mocks apropiados de dependencias externas
        - Casos de prueba completos
        - Nombres descriptivos de tests
        - No usar datos reales en tests

    - path: "docs/md/**/*.md"
      instructions: |
        Documentación del proyecto. Verifica:
        - Claridad y precisión
        - Actualizaciones con cambios de código
        - Enlaces correctos a specs
        - Ejemplos completos y funcionales

    - path: "openspec/**/*.md"
      instructions: |
        Especificaciones de OpenSpec. Verifica:
        - Consistencia con el código implementado
        - Testing plan completo
        - Requisitos bien definidos
        - No hay conflictos con specs existentes

    - path: "apps/web/prisma/**"
      instructions: |
        Schema de base de datos. Verifica:
        - Nombres en camelCase para campos
        - Índices en campos de búsqueda frecuente
        - Relaciones bidireccionales correctas
        - Tipos apropiados (Decimal para dinero, UUID para IDs)

  # Pre-merge checks
  pre_merge_checks:
    title:
      mode: warning
    description:
      mode: warning
    docstrings:
      mode: warning
      threshold: 70

  # Tools configuration
  tools:
    eslint:
      enabled: true
    markdownlint:
      enabled: false
